name: Build HTML5

on:
  workflow_dispatch:

jobs:
  html5:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Install Haxe
        uses: krdlab/setup-haxe@v1
        with:
          haxe-version: 4.3.6

      - name: Setup haxelib
        run: |
          mkdir -p ~/haxelib
          haxelib setup ~/haxelib

      - name: Install libraries
        run: |
          haxelib install lime --quiet
          haxelib install openfl --quiet
          haxelib install flixel --quiet
          haxelib install flixel-addons --quiet
          haxelib install flixel-ui --quiet
          haxelib install hscript --quiet
          haxelib install actuate --quiet
          haxelib install hxcpp --quiet

      - name: Setup Lime
        run: haxelib run lime setup

      - name: Build HTML5
        run: haxelib run lime test html5

      - name: Upload HTML5 Build
        uses: actions/upload-artifact@v4
        with:
          name: html5-build
          path: export/release/html5/bin
