name: Build HTML5

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Haxe
        uses: krdlab/setup-haxe@v1
        with:
          haxe-version: 4.3.2

      - name: Setup haxelib
        run: |
          mkdir -p ~/haxelib
          haxelib setup ~/haxelib

      - name: Install libraries
        run: |
          haxelib install lime 8.0.1 --quiet
          haxelib install openfl 9.3.2 --quiet
          haxelib install flixel 5.4.0 --quiet
          haxelib install flixel-addons 3.1.1 --quiet
          haxelib install flixel-ui 2.5.0 --quiet
          haxelib install hscript --quiet
          haxelib install actuate --quiet
          haxelib install hxcpp --quiet

      - name: Select library versions
        run: |
          haxelib set lime 8.0.1
          haxelib set openfl 9.3.2
          haxelib set flixel 5.4.0
          haxelib set flixel-addons 3.1.1
          haxelib set flixel-ui 2.5.0

      - name: Setup Lime
        run: |
          haxelib run lime setup

      - name: Build HTML5
        run: |
          haxelib run lime test html5

      - name: Upload HTML5 Build
        uses: actions/upload-artifact@v4
        with:
          name: B-Verse-HTML5
          path: export/release/html5/bin
